import Head from 'next/head'
import { Provider } from 'react-redux'
import { SessionProvider } from 'next-auth/react'
import store from '../src/redux/store'
import '../styles/globals.css'

function MyApp({ Component, pageProps: { session, ...pageProps } }) {
	return (
		<>
			<Head>
				<title>Papa`s Pizzeria </title>

				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin='true'
				/>
				<link
					href='https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,600;0,700;1,500&display=swap'
					rel='stylesheet'
				/>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<SessionProvider session={session}>
				<Provider store={store}>
					<Component {...pageProps} />
				</Provider>
			</SessionProvider>
		</>
	)
}

export default MyApp
