import Head from 'next/head'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Papa`s Pizzeria </title>

				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin />
				<link
					href='https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,600;0,700;1,500&display=swap'
					rel='stylesheet'
				/>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1>Ok</h1>
			</main>
		</div>
	)
}
